INSERT INTO [Shops] (  [Name],              [CountryId]  )
			VALUES  (   N'Big Book Shop',        1       ),
			        (   N'Books',                15      ),
					(   N'Книжный Рай',          23      ),
					(   N'Энциклопедия книг',    30      ),
					(   N'Книжный',              2       ),
					(   N'Libreria',             7       ),
					(   N'Grande libreria',      77      ),
					(   N'Gran librería',        10      ),
					(   N'Libro paraíso',        10      ),
					(   N'Книжный Домик',        3       ),
					(   N'Book Boom',            12      ),
					(   N'Buchboom',             55      ),
					(   N'Entrepôt de livres',   6       ),
					(   N'Paradis du livre',     69      ),
					(   N'Big Book Shop 2',      10      ),
			        (   N'Books 2',              11      ),
					(   N'Книжный Рай 2',        25      ),
					(   N'Энциклопедия книг 2',  34      ),
					(   N'Книжный 2',            28      ),
					(   N'Libreria 2',           71      ),
					(   N'Grande libreria 2',    76      ),
					(   N'Gran librería 2',      106     ),
					(   N'Libro paraíso 2',      109     ),
					(   N'Книжный Домик 2',      39      ),
					(   N'Book Boom 2',          18      ),
					(   N'Buchboom 2',           55      ),
					(   N'Entrepôt de livres 2', 69      ),
					(   N'Paradis du livre 2',   62      ),
					(   N'Big Book Shop 3',      123     ),
			        (   N'Books 3',              156     ),
					(   N'Книжный Рай 3',        201     ),
					(   N'Энциклопедия книг 3',  38      ),
					(   N'Книжный 3',            29      ),
					(   N'Libreria 3',           74      ),
					(   N'Grande libreria 3',    73      ),
					(   N'Gran librería 3',      156     ),
					(   N'Libro paraíso 3',      134     ),
					(   N'Книжный Домик 3',      31      ),
					(   N'Book Boom 3',          11      ),
					(   N'Buchboom 3',           52      ),
					(   N'Entrepôt de livres 3', 64      ),
					(   N'Paradis du livre 3',   66      )
